# Tau Bench Training Configuration for Llama-3.1-8B
# Based on tau_bench_config.yaml with adjustments for 8B model

defaults:
  - _self_
  - deepspeed_config@deepspeed_config.train: train
  - deepspeed_config@deepspeed_config.eval: eval
  - skyrl_gym_config: tau_bench

data:
  train_data: ["data/tau_bench_multi/train.parquet"]
  val_data: ["data/tau_bench_multi/validation.parquet"]
  retail_val_data: ["data/tau_bench_retail/validation.parquet"]  # Retail validation for comparison
  test_data:  # Test sets for final evaluation
    retail: "data/tau_bench_test/retail_test.parquet"
    airline: "data/tau_bench_test/airline_test.parquet"

trainer:
  placement:
    colocate_all: true
    colocate_policy_ref: true
    colocate_critic_reward: false
    policy_num_nodes: 1
    policy_num_gpus_per_node: 8
    critic_num_nodes: 1
    critic_num_gpus_per_node: 8
    ref_num_nodes: 1
    ref_num_gpus_per_node: 8
    reward_num_nodes: 1
    reward_num_gpus_per_node: 8
  
  sequence_parallel_backend: "ulysses"
  strategy: fsdp2
  
  policy:
    model:
      path: "unsloth/Meta-Llama-3.1-8B-Instruct"  # 8B model
    deepspeed_config: ${deepspeed_config.train}
    optimizer_config:
      lr: 2.0e-7  # Lower learning rate for 8B model
      adam_betas: [0.9, 0.999]
      weight_decay: 5e-2
      max_grad_norm: 0.5
      offload_after_step: true
      num_warmup_steps: 50
    fsdp_config:
      cpu_offload: false
      reshard_after_forward: true
      fsdp_size: -1
    sequence_parallel_size: 1
  
  ref:
    model:
      path: "unsloth/Meta-Llama-3.1-8B-Instruct"  # 8B model
    fsdp_config:
      cpu_offload: false
      reshard_after_forward: true
      fsdp_size: -1
    sequence_parallel_size: 1
  
  critic:
    model:
      path: "unsloth/Meta-Llama-3.1-8B-Instruct"  # 8B model
    deepspeed_config: ${deepspeed_config.train}
    optimizer_config:
      lr: 5.0e-6
      adam_betas: [0.9, 0.999]
      weight_decay: 5e-2
      max_grad_norm: 0.5
      offload_after_step: true
      num_warmup_steps: 50
    fsdp_config:
      cpu_offload: false
      reshard_after_forward: true
      fsdp_size: -1
    sequence_parallel_size: 1
  
  reward:
    model:
      path: "unsloth/Meta-Llama-3.1-8B-Instruct"  # 8B model
    fsdp_config:
      cpu_offload: false
      reshard_after_forward: true
      fsdp_size: -1
    sequence_parallel_size: 1
  
  algorithm:
    use_kl_loss: true
    kl_loss_coef: 0.02
    use_critic_value: true
    use_critic_loss: true
    enable_ppo_loss: true
    enable_critic_loss: true
    enable_reward: true
    n_minibatches: 8  # Adjusted for 8B model
    advantage_normalization: true
    advantage_batch_normalize: false
    value_head_prefix: "value_head"
    ppo_loss_type: "regular"
    loss_reduction: "token_mean"
    lambd: 1.0
    gamma: 1.0
    eps_clip_low: 0.1
    eps_clip_high: 0.1
    clip_ratio_c: 3.0
    value_clip: 0.1
    normalize_reward: true

  gradient_checkpointing: true
  gradient_checkpointing_use_reentrant: false
  seed: 42
  resume_mode: latest
  resume_path: null
  ckpt_path: "${oc.env:HOME}/ckpts/tau_bench"
  max_ckpts_to_keep: 3
  ckpt_interval: 5  # Save checkpoints more frequently
  hf_save_interval: 20
  export_path: "${oc.env:HOME}/exports/tau_bench"
  bf16: true
  epochs: 100  # Increased for better convergence
  update_epochs_per_batch: 1
  train_batch_size: 32  # Reduced for 8B model
  policy_mini_batch_size: 8  # Reduced for 8B model
  critic_mini_batch_size: 8  # Reduced for 8B model
  micro_train_batch_size_per_gpu: 1
  micro_forward_batch_size_per_gpu: 1  # Reduced for 8B model
  update_ref_every_epoch: false
  use_sample_packing: false  # Disabled because flash attention is not available
  eval_batch_size: 16  # Reduced for 8B model
  eval_before_train: true
  eval_interval: 5  # Evaluate every 5 epochs
  max_prompt_length: 16384  # Keep same context length
  flash_attn: false
  disable_fast_tokenizer: false
  target_modules: "all-linear"
  use_orm_score: false
  project_name: "tau_bench_rl"
  run_name: "tau_bench_llama3_1_8b_v1"
  logger: "wandb"
  dump_data_batch: false
  dump_eval_results: true  # Enable trajectory dumping

generator:
  model_dtype: "bfloat16"
  run_engines_locally: true
  num_inference_engines: 2
  backend: "vllm"
  weight_sync_backend: "nccl"
  inference_engine_tensor_parallel_size: 4
  n_samples_per_prompt: 3
  async_engine: true
  batched: false  # Important for multi-turn conversations
  max_input_length: 16384  # Keep same context length
  vllm_v1_disable_multiproc: true
  enable_prefix_caching: true
  enable_chunked_prefill: true
  max_num_batched_tokens: 16384  # Reduced for 8B model
  enforce_eager: false
  gpu_memory_utilization: 0.65  # Reduced for 8B model
  max_num_seqs: 128  # Reduced for 8B model
  remote_inference_engine_urls: ["127.0.0.1:8001"]
  max_turns: 20  # Multi-turn conversations
  
  override_existing_update_group: "auto"
  
  # Sampling parameters for generation
  sampling_params:
    max_generate_length: 1024
    temperature: 0.8
    top_p: 0.95
    min_p: 0.0
    top_k: -1

  # Native tool calling configuration
  use_native_tool_calling: true
  use_conversation_multi_turn: true
  eval_n_samples_per_prompt: 1  # For evaluation

environment:
  env_class: "tau_bench"
  skyrl_gym:
    tau_bench:
      user_strategy: "llm"
      user_model: "gpt-4o"
      user_provider: "openai"
      max_turns: 10
      use_native_tool_calling: true
    max_env_workers: 16