# Tau Bench Training Configuration
# Based on SkyRL ppo_base_config.yaml with tau_bench specific settings

defaults:
  - _self_
  - deepspeed_config@deepspeed_config.train: train
  - deepspeed_config@deepspeed_config.eval: eval
  - skyrl_gym_config: tau_bench

data:
  train_data: ["${oc.env:HOME}/data/tau_bench/train.parquet"]
  val_data: ["${oc.env:HOME}/data/tau_bench/validation.parquet"]

trainer:
  placement:
    colocate_all: true
    colocate_policy_ref: true
    colocate_critic_reward: false
    policy_num_nodes: 1
    policy_num_gpus_per_node: 8
    critic_num_nodes: 1
    critic_num_gpus_per_node: 8
    ref_num_nodes: 1
    ref_num_gpus_per_node: 8
    reward_num_nodes: 1
    reward_num_gpus_per_node: 8
  
  sequence_parallel_backend: "ulysses"
  strategy: fsdp2
  
  policy:
    model:
      path: "Qwen/Qwen2.5-7B-Instruct"
    deepspeed_config: ${deepspeed_config.train}
    optimizer_config:
      lr: 1.0e-6
      adam_betas: [0.9, 0.999]
      weight_decay: 1e-2
      max_grad_norm: 1.0
      offload_after_step: true
      num_warmup_steps: 0
    fsdp_config:
      cpu_offload: false
      reshard_after_forward: true
      fsdp_size: -1
    sequence_parallel_size: 1
    use_torch_compile: false
    record_memory: false
  
  ref:
    model:
      path: "Qwen/Qwen2.5-7B-Instruct"
    sequence_parallel_size: 1
    deepspeed_config: ${deepspeed_config.eval}
    fsdp_config:
      cpu_offload: true
      reshard_after_forward: true
      fsdp_size: -1
      
  critic:
    model:
      path: null
    deepspeed_config: ${deepspeed_config.train}
    optimizer_config:
      lr: 5.0e-6
      adam_betas: [0.9, 0.999]
      weight_decay: 1e-2
      max_grad_norm: 1.0
      offload_after_step: true
      num_warmup_steps: 0
    fsdp_config:
      cpu_offload: false
      reshard_after_forward: true
      fsdp_size: -1
    sequence_parallel_size: 1
    
  reward:
    model:
      path: null
    deepspeed_config: ${deepspeed_config.eval}
    fsdp_config:
      cpu_offload: true
      reshard_after_forward: true
      fsdp_size: -1
    sequence_parallel_size: 1
    
  algorithm:
    advantage_estimator: "grpo"
    kl_target: null
    init_kl_coef: 0.0
    use_kl_estimator_k3: true
    use_abs_kl: false
    use_kl_in_reward: false
    use_kl_loss: true
    kl_loss_coef: 0.001
    advantage_batch_normalize: false
    value_head_prefix: "value_head"
    ppo_loss_type: "regular"
    loss_reduction: "token_mean"
    lambd: 1.0
    gamma: 1.0
    eps_clip_low: 0.2
    eps_clip_high: 0.2
    clip_ratio_c: 3.0
    value_clip: 0.2
    normalize_reward: true

  gradient_checkpointing: true
  gradient_checkpointing_use_reentrant: false
  seed: 42
  resume_mode: latest
  resume_path: null
  ckpt_path: "${oc.env:HOME}/ckpts/tau_bench"
  max_ckpts_to_keep: 3
  ckpt_interval: 10
  hf_save_interval: 20
  export_path: "${oc.env:HOME}/exports/tau_bench"
  bf16: true
  epochs: 50
  update_epochs_per_batch: 1
  train_batch_size: 256
  policy_mini_batch_size: 64
  critic_mini_batch_size: 64
  micro_train_batch_size_per_gpu: 1
  micro_forward_batch_size_per_gpu: 2
  update_ref_every_epoch: false
  use_sample_packing: true
  eval_batch_size: 128
  eval_before_train: true
  eval_interval: 5
  max_prompt_length: 4096
  flash_attn: true
  disable_fast_tokenizer: false
  target_modules: "all-linear"
  use_orm_score: false
  project_name: "tau_bench_rl"
  run_name: "tau_bench_qwen7b_v1"
  logger: "wandb"
  dump_data_batch: false
  dump_eval_results: true

generator:
  model_dtype: "bfloat16"
  run_engines_locally: true
  num_inference_engines: 2
  backend: "vllm"
  weight_sync_backend: "nccl"
  inference_engine_tensor_parallel_size: 4
  n_samples_per_prompt: 3
  async_engine: true
  batched: false  # Important for multi-turn conversations
  max_input_length: 4096
  vllm_v1_disable_multiproc: true
  enable_prefix_caching: true
  enable_chunked_prefill: true
  max_num_batched_tokens: 8192
  enforce_eager: false
  gpu_memory_utilization: 0.7
  max_num_seqs: 256
  remote_inference_engine_urls: ["127.0.0.1:8001"]
  max_turns: 20  # Multi-turn conversations
  
  override_existing_update_group: "auto"
  
  # Sampling parameters for generation
  sampling_params:
    max_generate_length: 2048
    temperature: 0.7
    top_p: 0.9
    min_p: 0.0
    top_k: -1

  # Use conversation-based format for multi-turn
  use_conversation_multi_turn: true

  # Evaluation sampling parameters
  eval_sampling_params:
    max_generate_length: 2048
    temperature: 0.0
    top_p: 1.0
    min_p: 0.0
    top_k: -1

  # Number of samples per prompt for evaluation
  eval_n_samples_per_prompt: 1

  # Zero reward for non-stop generations
  zero_reward_on_non_stop: true

environment:
  env_class: "tau_bench"
  skyrl_gym:
    max_env_workers: 16
    tau_bench:
      user_strategy: "llm"
      user_model: "gpt-4o"
      user_provider: "openai"
      max_turns: 20 