model_name_or_path: Qwen/Qwen2.5-3B-Instruct
dataset: tau_bench_full
template: qwen
cutoff_len: 16384
overwrite_cache: true

finetuning_type: lora
lora_target: all
lora_rank: 64
lora_alpha: 128
lora_dropout: 0.1

output_dir: saves/qwen2_5_3b_tau_bench_lora
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1

bf16: true
gradient_checkpointing: true
logging_steps: 10
save_steps: 500
save_total_limit: 2

tool_format: default
train_on_prompt: false
report_to: none