model_name_or_path: Qwen/Qwen2.5-7B-Instruct
dataset: tau_bench_balanced
template: qwen
cutoff_len: 8192
overwrite_cache: true

quantization_bit: 4
quantization_method: bitsandbytes
bnb_4bit_compute_dtype: bfloat16
bnb_4bit_use_double_quant: true
bnb_4bit_quant_type: nf4

finetuning_type: lora
lora_target: q_proj,v_proj,k_proj,o_proj,gate_proj,up_proj,down_proj
lora_rank: 128
lora_alpha: 256
lora_dropout: 0.05
use_rslora: true

output_dir: saves/qwen2_5_7b_tau_bench_qlora
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 2.0e-4
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1

bf16: true
gradient_checkpointing: true
upcast_layernorm: true
logging_steps: 10
save_steps: 250
save_total_limit: 2

optim: paged_adamw_32bit
tool_format: default
train_on_prompt: false
report_to: none