model_name_or_path: Qwen/Qwen2.5-3B-Instruct
dataset: tau_bench_full
template: qwen
cutoff_len: 16384
overwrite_cache: true

finetuning_type: full

output_dir: saves/qwen2_5_3b_tau_bench_full
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 2.0e-5
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_steps: 100

bf16: true
gradient_checkpointing: true
logging_steps: 10
save_steps: 200
save_total_limit: 2

tool_format: default
train_on_prompt: false
report_to: none

deepspeed: examples/deepspeed/ds_z2_config.json