# @package environment.skyrl_gym
# Tau Bench specific configuration for skyrl_gym

# Number of background workers for env step calls
max_env_workers: 16

# Tau Bench specific configuration
tau_bench:
  # User simulation settings
  user_strategy: "llm"  # Options: "llm", "react", "verify", "reflection"
  user_model: "gpt-4o"  # Model for user simulation
  user_provider: "openai"  # Provider for user simulation
  
  # Conversation settings  
  max_turns: 20  # Maximum turns per conversation
  
  # Environment settings
  timeout: 120  # Timeout for environment operations (seconds)
  
  # Debugging and logging
  log_conversations: true  # Log full conversations for debugging
  log_tool_calls: true  # Log individual tool calls
  
  # Performance settings
  cache_environments: true  # Cache environment instances
  parallel_user_sim: false  # Run user simulation in parallel (experimental) 